# Generated by Django 5.1.7 on 2025-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://imgs.search.brave.com/Qew1jLRC8BCdLELrrPbZ6MW0SAv5reqcRh0pIhojvcM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA4LzI2Lzc3LzI5/LzM2MF9GXzgyNjc3/Mjk1NF9IcU9pMVRJ/cUVwbkZjbXJsR1Qx/QWxSRHo5RVd4M0tk/cS5qcGc', max_length=500),
        ),
    ]
